#홈페이지에서 API서비스 신청시 받은 Appkey, Appsecret 값 설정
APP_KEY: "PSwLBtF0WVCyEJ2vRISn4cjzfIFrfZcW4iku"
APP_SECRET: "b8KUcPZlTc1nXj1Vjf9x+wnn9CQveXtZr/yvSYfZSlYedZTC+VmJB0Vnjztg41Oh4DeSoCm2UoNrClXX/61e18BV8QYX2ixYAMH0rmAC281Y4U1Cm9Nq4FacAtSeK+UbIB4Iu+y9ZM0f/SfmBOJlQSsZ8vxcAcQclUa6jFhQSyRqUGQIDo4="

#계좌번호 앞 8자리
CANO: "46605641"
#계좌번호 뒤 2자리
ACNT_PRDT_CD: "01"

#HTS ID
HTS_ID: "nice234"

#실전투자
URL_BASE: "https://openapi.koreainvestment.com:9443"
#모의투자
# URL_BASE: "https://openapivts.koreainvestment.com:29443"

#디스코드 웹훅 URL
DISCORD_WEBHOOK_URL: "https://discord.com/api/webhooks/1318767242883760210/A2eEWfQ3qtK2A6hOlFYTGXs7I_5Kj0ZcXQ_X1iPKlP4cXbKONZtd6YlfH0Tq4pe_lkkp"