#홈페이지에서 API서비스 신청시 받은 Appkey, Appsecret 값 설정
APP_KEY: "PS0TUYsR5OA41S3t2uXAbCaCuraTVaazYgvR"
APP_SECRET: "FE0tHqX60kZM/bKKi4hhVJxYN2X8ZmiRwhLE3RSDMXeSb2BRNPPR4ZQrcKKuFoEIpJLBMGF3RAKPy39I1zRx+I/fqIKOJQCd+ZWNyNTZ5mrvMOzbwl+/iu/0yv39u711MK9SBQBrBFya+jNUo0IjU27bWW6WZ3TE1PY76kcyC4/qJQG8Xo0="

#계좌번호 앞 8자리
CANO: "64759294"
#계좌번호 뒤 2자리
ACNT_PRDT_CD: "01"

#HTS ID
HTS_ID: "nice234"

#실전투자
URL_BASE: "https://openapi.koreainvestment.com:9443"
#모의투자
# URL_BASE: "https://openapivts.koreainvestment.com:29443"

#디스코드 웹훅 URL
DISCORD_WEBHOOK_URL: "https://discord.com/api/webhooks/1326179037575647232/0WUgY2z_TEloYfexYecrCiNvHLX9d4fhw6OlxcfpvXF4GQ9_ZV9uYoAWstjMY2wb1U6G"

